apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-ci-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi-ci-test
  template:
    metadata:
      labels:
        app: flaskapi-ci-test
    spec:
      containers:
        - name: flaskapi-ci-test
          image: shivansh760/flask-api:d2ce73d1982197ea1787abec3752a643863abd57
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
