apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-ci-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapi-ci-test
  template:
    metadata:
      labels:
        app: flaskapi-ci-test
    spec:
      containers:
        - name: flaskapi-ci-test
          image: shivansh760/flask-api:0c17db943e08741560e8deade2746940ea3d12cc
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
