apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: NzQ1NjczNTc4ODNjNGQwMzUyZmJmZDVjYzM3ZWM1ZTAyMjI4MDgxM2Q2ZTI2Zjg1OGM4MTI3ZGExYTI0YzBkMQ==
